spring.application.name=frontendThymeleaf

logging.level.root=info
logging.level.com.betacom=debug

logging.pattern.console=  %d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\\(%F:%L\\) - %msg%n
logging.file=./frontendJPA.log

jpa.backend=http://localhost:9090/rest/